name: core
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.8.0

  # This is our modular
  mdependencies:
    path: ../dependencies
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

flutter: